"""empty message

Revision ID: 14861cc0216e
Revises: ad48ddd4a393
Create Date: 2019-04-27 15:15:04.801268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14861cc0216e'
down_revision = 'ad48ddd4a393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counter')
    # ### end Alembic commands ###
